version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "28000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - ~/mongodbdata:/data/db
